version: '3'

services:

    keycloak:
        image: jboss/keycloak:15.0.0
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: ${KEYCLOAK_USER}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        volumes:
            - ./certs/keycloak:/etc/x509/https
        ports:
            - 8443:8443
        depends_on:
            - postgres

    postgres:
        image: postgres:13.3-alpine3.14
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password

volumes:
    postgres_data:
